# pyproject.toml 
# contains the metadata necessary for building and packaging the library

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tic-tac-toe"
version = "1.0.0"